name: hupomnesis
description: Write your notes in Markdown!

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_local_notifications: ^0.5.2
  rxdart: ^0.21.0
  path_provider: ^0.5.0
  test: ^1.5.3
  flutter_staggered_grid_view: ^0.2.7
  flutter_sticky_header: ^0.3.4
  flutter_markdown: ^0.2.0
  flutter_html: ^0.10.0
  sqflite: ^1.1.0
  dynamic_theme: ^1.0.0
  shared_preferences: ^0.5.3+1


flutter:
  uses-material-design: true
  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 200
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 400
  - family:  StyleIcons
    fonts:
      - asset: assets/fonts/StyleIcons.ttf

  # To add assets to your application
# assets:
