name: hupomnesis
description: Flutter project for the contest 'Flutter Create'.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.0.2
  shared_preferences: ^0.5.1+1
  flutter_local_notifications: ^0.5.2
  page_view_indicator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
  - family: Roboto-Light
    fonts:
    - asset: assets/fonts/Roboto-Light.ttf
  - family: Roboto-Bold
    fonts:
    - asset: assets/fonts/Roboto-Bold.ttf
  